language: java
cache:
  directories:
  - "node_modules"
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3
before_install:
  - npm install drafter nodejs
script:
  - nodejs parse.js
